- src/sentry_github/plugin.py
- tests/sentry_github/test_plugin.py
already reviewed see https://github.com/getsentry/sentry-github/pull/37
> move github plugin to react

- src/sentry_plugins/github/plugin.py
fixes SENTRY-1TR
@getsentry/infrastructure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-plugins/3)
> fix UnicodeEncodeError in github issue autocomplete

- setup.cfg
- setup.py
- src/sentry_plugins/jira_ac/__init__.py
- src/sentry_plugins/jira_ac/forms.py
- src/sentry_plugins/jira_ac/models.py
- src/sentry_plugins/jira_ac/plugin.py
- src/sentry_plugins/jira_ac/south_migrations/0001_initial.py
- src/sentry_plugins/jira_ac/templates/base.html
- src/sentry_plugins/jira_ac/templates/config.html
- src/sentry_plugins/jira_ac/templates/error.html
- src/sentry_plugins/jira_ac/templates/signin.html
- src/sentry_plugins/jira_ac/templates/widget.html
- src/sentry_plugins/jira_ac/urls.py
- src/sentry_plugins/jira_ac/utils.py
- src/sentry_plugins/jira_ac/views.py
still working on a few ui things, but this is pretty much done
@getsentry/plugins @getsentry/ui
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-plugins/13)
> add jira atlassian connect plugin

- src/sentry_plugins/jira_ac/views.py
@getsentry/plugins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-plugins/17)
> update getsentry.com --> sentry.io

- src/sentry_plugins/jira/plugin.py
> make jira unauthorized message clearer

- src/sentry_plugins/bitbucket/endpoints/webhook.py
- src/sentry_plugins/bitbucket/testutils.py
I was relying on some data being present that isn't always
> fix bitbucket webhook data assumptions

- src/sentry_plugins/bitbucket/client.py
> don't try to decode empty response bodies

- src/sentry_plugins/bitbucket/endpoints/webhook.py
- src/sentry_plugins/bitbucket/plugin.py
- src/sentry_plugins/bitbucket/testutils.py
- tests/bitbucket/endpoints/test_webhooks.py
the user object is not always available. fixes SENTRY-3Q8
> parse name from raw 

- src/sentry_plugins/slack/plugin.py
- tests/slack/test_plugin.py
Adds referrer param for Slack plugin.
Relies of https://github.com/getsentry/sentry/pull/5881
> adding slack referrer url param

- src/sentry_plugins/bitbucket/endpoints/webhook.py
- tests/bitbucket/endpoints/test_webhooks.py
> fix(bitbucket): handle invalid email addresses in push webhook

- src/sentry_plugins/github/endpoints/webhook.py
> fix(github): Truncate author name when updating

- src/sentry_plugins/jira/plugin.py
- tests/jira/test_plugin.py
> fix(jira): Handle addon users without email addresses in autocomplete

- setup.py
- src/sentry_plugins/vsts/client.py
- src/sentry_plugins/vsts/plugin.py
- tests/vsts/test_plugin.py
- Support markdown text for description/comments, and automatically convert to HTML
- Dont use description- it doesn't seem to be visible by default
- Dont use link- it doesnt seem visible/usable by default and causes conflicts
> fix(vsts): Various improvements

- .travis.yml
https://github.com/getsentry/sentry/commit/198ce58bdc25a4ee7dd188648631f07cc9a16264#diff-354f30a63fb0907d4ad57269548329e3
> try to fix travis

- src/sentry_plugins/bitbucket/client.py
uses the "next" field for pagination
> fix(Bitbucket): Follow commit pagination

- src/sentry_plugins/slack/plugin.py
Fixes: [SENTRY-5SW
](https://sentry.io/share/issue/5335afbf14db4d789111abe00f99927b/)
> fix(slack): Fix unicode formating

- src/sentry_plugins/bitbucket/client.py
- src/sentry_plugins/bitbucket/testutils.py
- tests/bitbucket/test_repository_provider.py
> fix(bitbucket): commit file changes

- .vscode/extensions.json
- src/sentry_plugins/asana/client.py
> fix(asana): Fix Asana API - requires projects array

- README.rst
- src/sentry_plugins/bitbucket/README.rst
- src/sentry_plugins/github/README.rst
- src/sentry_plugins/gitlab/README.rst
- src/sentry_plugins/slack/README.rst
> docs: Fix links

- src/sentry_plugins/bitbucket/testutils.py
- src/sentry_plugins/victorops/plugin.py
- tests/victorops/test_plugin.py
Added issue id as well as project id to victorops payload
Fixes https://github.com/getsentry/sentry-plugins/issues/252
> feat(victorops): Add issue and project id
